### ISSUE TITLE
Numpy dependency is incompatible with aiida-core[atomic_tools]

### ISSUE THREAD

**Issue by yakutovicha** [CasperWA/voila-optimade-client#156]
Please modify the numpy dependency version, which currently looks as:
https://github.com/CasperWA/voila-optimade-client/blob/706ab1f48914db8a1ea69f9f59507285449730ce/requirements.txt#L8

to `>=1.17`, so that they can be installed with `aiida-core[atomic_tools]` in the same environment without conflicts.

**Comment by CasperWA** [comment]
Is this needed for the AiiDA lab version? Then it becomes an issue you can raise in [`aiidalab/aiidalab-optimade`](https://github.com/aiidalab/aiidalab-optimade).
AiiDA core is not a dependency of this package, so there is no need to satisfy the incompatibilities with `aiida-core` in this repository.

**Comment by CasperWA** [comment]
This issue has been moved to aiidalab/aiidalab-optimade#2, where it is applicable. Closing it here.

**Comment by yakutovicha** [comment]
Well, I think the issue is for this package because the numpy dependency is specified here. In any environment where one installs the `optimade-client` together with `aiida-core[atomic_tools]` this issue is going to pop up (for the time being as a warning, but later as an error, when pip is going to introduce stricter rules for the dependency handling).

**Comment by CasperWA** [comment]
I would consider that an issue of `aiida-core` and not `optimade-client`, since `optimade-client` is on the newest version, i.e., `aiida-core` would have to try and keep up. So if you wish to combine the two, you need to be aware of the shortcomings of `aiida-core`, not `optimade-client`.

Note, `optimade-client` is `aiida-core` independent.

**Comment by yakutovicha** [comment]
Okay, I asked the question about the numpy dependency of `aiida-core` in the aiidateam chat. In the meanwhile, could you please let me know if the `optimade-client` would work fine with `numpy~=1.17`, or, to be more specific, with `0.17.5`?

> Note, `optimade-client` is `aiida-core` independent.

sure

**Comment by CasperWA** [comment]
After further discussion with @yakutovicha, it may make sense to simply extend the allowed versions for `numpy` after all to accommodate out-of-date packages that depend on older versions of `numpy` and wish to use `optimade-client`.

**Comment by CasperWA** [comment]
See other discussions in aiidalab/aiidalab-optimade#2 and aiidalab/aiidalab-optimade#3.

**Comment by CasperWA** [comment]
See the [closing comment](https://github.com/CasperWA/voila-optimade-client/pull/157#issuecomment-696607094) in #157.
