### ISSUE TITLE
Possibly implement OptimadeQueryWidget from aiidalab/aiidalab-optimade

### ISSUE THREAD

**Issue by CasperWA** [CasperWA/voila-optimade-client#158]
See [this comment](https://github.com/aiidalab/aiidalab-docker-stack/pull/121#issuecomment-694309809).

There is a use case to have a combined provider+filters widget importable from the `optimade-client` package.

**Comment by yakutovicha** [comment]
Ok, so what I would suggest doing, is move the widget  `OptimadeQueryWidget` here, in `optimade-client`, but for the time being keep it importable from the `aiidalab-optimade`(adding a deprecation warning, that this won't be working soon).

**Comment by CasperWA** [comment]
> Ok, so what I would suggest doing, is move the widget `OptimadeQueryWidget` here, in `optimade-client`, but for the time being keep it importable from the `aiidalab-optimade`(adding a warning, that this won't be working soon).

Right. That would then still demand the installation of `aiidalab-optimade` in the docker stack for now then...

**Comment by yakutovicha** [comment]
> Right. That would then still demand the installation of `aiidalab-optimade` in the docker stack for now then...

yes, I also realized that. But it is fine as a temporary solution, I think.

Do you mind if I do all together here: https://github.com/aiidalab/aiidalab-docker-stack/pull/119?

**Comment by CasperWA** [comment]
> Do you mind if I do all together here: [aiidalab/aiidalab-docker-stack#119](https://github.com/aiidalab/aiidalab-docker-stack/pull/119)?

Let's just keep it in aiidalab/aiidalab-docker-stack#121 for now, since I still have to first update both `aiidalab-optimade` and `voila-optimade-client` accordingly. And then again later update `aiidalab-optimade` again ...

**Comment by CasperWA** [comment]
So when doing this, I found the reason why this exists in the `aiidalab/aiidalab-optimade` repository (and the `aiidalab-optimade` package) and not in the present repository and package: The `aiidalab-widgets-base`'s `StructureManagerWidget` expects certain class instances for the `structure` attribute, which does not match with the general implementation in the current package.
Even if the widget is implemented in the current package, it would still need to be wrapped or "treated" in each application using it together with `StructureManagerWidget` to make sure the `structure` widget correctly contains either an `ase.Atoms` or `aiida.orm.StructureData` instance. This is, however, quite easy, since the current `optimade.adapters.Structure` can be easily converted to both data types, but it would still need to be done each and every single time.

Instead, by having this extra widget in the AiiDAlab-specific `aiidalab-optimade` package, we can ensure that the `structure` attribute is always the correct instance, and one can import the `OptimadeQueryWidget` from `aiidalab-optimade`.

**Comment by CasperWA** [comment]
Another solution may be to implement this widget, or a simili in `aiidalab-widgets-base`? That might be better to not confuse imports from `aiidalab_optimade` and `optimade_client`?

**Comment by yakutovicha** [comment]
Thanks @CasperWA for your suggestions.

[motivation]
Just for clarification: the ultimate goal for me would be to remove the installation of the OPTIMADE client from the [Dockerfile](https://github.com/aiidalab/aiidalab-docker-stack/blob/develop/Dockerfile#L96-L100). It was put there as a temporary solution and, with the introduction of the PyPI package, can be avoided.

Based on this I wouldn't like to have it in the optimade AiiDAlab application, as we tend not to put AiiDAlab applications as the dependencies.

[possible solutions]
What I was intending to propose is to move the widget to the `optimade-client` package. I would add an `aiida` entry in the [extras_require](https://github.com/CasperWA/voila-optimade-client/blob/9291a3a7d79f57e98a3e41249881bdb98fc5ee1f/setup.py#L33) to install the aiida-specific dependencies only when we work with AiiDA.

> Another solution may be to implement this widget or a simili in `aiidalab-widgets-base`? 

This is, of course, possible and this would, of course, allow removing the installation from the Dockerfile I mentioned earlier. Personally, I would prefer to have the AiiDAlab-specific widget be importable from one well-defined place (and for me this place is `optimade-client`) instead of having it spread out through different packages.

**Comment by yakutovicha** [comment]
Imagine the following use case:

I work with AiiDA and I want to try the OPTIMADE widget to import the structure in pure Jupyter (not AiiDAlab). I don't need the full `aiidalab` package, I just need one little tool that returns me the `StructureData` object. In that case, I would prefer to install the OPTIMADE client alone using the following command:
```shell
$ pip install optimade-client[aiida]
```

I think that properly satisfying such a use case would only be possible if the AiiDA-OPTIMADE widget is available through the `optimade-client` package.

**Comment by CasperWA** [comment]
> Imagine the following use case:
> 
> I work with AiiDA and I want to try the OPTIMADE widget to import the structure in pure Jupyter (not AiiDAlab). I don't need the full `aiidalab` package, I just need one little tool that returns me the `StructureData` object. In that case, I would prefer to install the OPTIMADE client alone using the following command:
> 
> ```shell
> $ pip install optimade-client[aiida]
> ```
> 
> I think that properly satisfying such a use case would only be possible if the AiiDA-OPTIMADE widget is available through the `optimade-client` package.

It's already (sort of) available. The simplest fix here would be to add a condition in the `StructureManagerWidget` to handle OPTIMADE Structure classes and correctly use their built-in conversion functionality to retrieve a `StructureData` node.

**Comment by CasperWA** [comment]
Newest development is to implement it in `aiidalab-widgets-base` instead (see aiidalab/aiidalab-widgets-base#131).

**Comment by CasperWA** [comment]
This issue has been settled. `OptimadeQueryWidget` is implemented in `aiidalab-widgets-base` and will be deprecated in `aiidalab-optimade`.
