### ISSUE TITLE
Missing provider list in embedded mode

### ISSUE THREAD

**Issue by csadorf** [CasperWA/voila-optimade-client#235]
I just tested the latest version of the optimade-client in the QE app and found that it appears that the provider list is missing (see screenshot below).

![Screen Shot 2020-12-03 at 5 57 31 PM](https://user-images.githubusercontent.com/1441208/101061812-332c3f80-3591-11eb-856f-2de4a8d801e7.png)

**Comment by CasperWA** [comment]
How did you update the `optimade-client` dependency here? I would think that when it's installed during the setup of AiiDAlab it should be fine, as the new dependency `ipywidgets-extended` will be included and installed properly (similar to `widget-periodictable`).

**Comment by csadorf** [comment]
The OPTIMADE package is installed as part of this command: https://github.com/aiidalab/aiidalab-docker-stack/blob/6a320954b4d2b2746ae5040e49c106bdd988ed61/Dockerfile#L59-L62

The requirements are defined here: https://github.com/aiidalab/aiidalab-docker-stack/blob/6a320954b4d2b2746ae5040e49c106bdd988ed61/requirements.txt#L129

It appears that both the correct version of aiidalab-optimade and the `ipywidgets-extended` are installed: https://pipelines.actions.githubusercontent.com/UZDhFQCGuQw9KCSChAfSZ48nvz1K8BLvAgmfx6x8FHiKEca1rg/_apis/pipelines/1/runs/167/signedlogcontent/3?urlExpires=2020-12-08T16%3A08%3A06.6087312Z&urlSigningMethod=HMACV1&urlSignature=rh09LxkTbLZHSBDXuintB6hF1jf77VrPCMc3HFfBQko%3D

**Comment by CasperWA** [comment]
Then I don't understand exactly why it's not working :/

**Comment by csadorf** [comment]
> Then I don't understand exactly why it's not working :/

@casperWa I can try to debug this further, but just so I understand, you are pretty sure that this would likely be caused by `ipywidgets-extended` either not being installed and/or not activated, correct?

**Comment by CasperWA** [comment]
> > Then I don't understand exactly why it's not working :/
> 
> @CasperWA I can try to debug this further, but just so I understand, you are pretty sure that this would likely be caused by `ipywidgets-extended` either not being installed and/or not activated, correct?

Yes, because the widgets that are missing are the only ones using `ipywidgets-extended`, and that is also the only major change, I believe.
