### ISSUE TITLE
add optimade to setup.py?

### ISSUE THREAD

**Issue by broeder-j** [CasperWA/voila-optimade-client#24]
Hi. Should optimade not be a requirement, which should be installed if aiidalab-optimade is installed? If I install this app with aiidalab, and perform a simple querry it fails, because it cannot find optimade (which is not installed).

```
~/apps/aiidalab-optimade/aiidalab_optimade/subwidgets/filter_inputs.py in parse(self, key, value)
     61         if func is None:
     62             return self.__default__(value)
---> 63         return func(value)
     64 
     65     def __default__(self, value: str) -> str:  # pylint: disable=no-self-use

~/apps/aiidalab-optimade/aiidalab_optimade/subwidgets/filter_inputs.py in elements(value)
    143     def elements(value: str) -> str:
    144         """Check against optimade-python-tools list of elememnts"""
--> 145         from optimade.models.utils import CHEMICAL_SYMBOLS
    146 
    147         results = []

ModuleNotFoundError: No module named 'optimade'
```

**Comment by CasperWA** [comment]
Indeed it should, and indeed [it is](https://github.com/aiidalab/aiidalab-optimade/blob/master/setup.py#L20).
However, the underlying installation mechanism of AiiDA lab applications is in flux at the moment, and is currently being updated. Check [here](https://github.com/aiidalab/aiidalab/issues/41) for more information.

On another note; thanks for the interest!
I am currently finishing a more general-access-friendly version of this package, in the form of removing the AiiDA dependency completely from the base application and depending more on the `optimade` package ([optimade-python-tools](https://github.com/Materials-Consortia/optimade-python-tools)). The working branch for this is [`pure_jupyter_version`](https://github.com/aiidalab/aiidalab-optimade/tree/pure_jupyter_version).
Within the week I should have a working notebook published on mybinder.

**Comment by CasperWA** [comment]
I will close this issue, since `optimade` _is_ in `setup.py`. For installing this in AiiDA lab it is a matter of updating the AiiDA lab installer, see issue aiidalab/aiidalab#41.
