### ISSUE TITLE
Issue with CIF export

### ISSUE THREAD

**Issue by giovannipizzi** [CasperWA/voila-optimade-client#31]
I tried exporting a CIF, and when importing in VESTA I get zero atoms.

The file is attached here (with .txt extension) for reference.
ASE seems to be able to read it, but I guess it has a very simple parser.

[optimade_structure_11794.cif.txt](https://github.com/aiidalab/aiidalab-optimade/files/4610987/optimade_structure_11794.cif.txt)

This checking tool should help: https://checkcif.iucr.org
I think a few pointers are that `_atom_site_label` should be unique (the error is `An _atom_site_label occurs more than once in the atom list.`). Moreover I think it is needed to have the fractional coordinates, rather than the cartesian (also because you are not defining a 3x3 cell, but just a, b, c and angles, so in principle one does not know how to orient the axes.

**Comment by CasperWA** [comment]
The converter is implemented in `optimade-python-tools`, I will forward the issue there.

**Comment by CasperWA** [comment]
Forwarded to Materials-Consortia/optimade-python-tools#271
