### ISSUE TITLE
Do not try to url encode the URL by hand

### ISSUE THREAD

**Issue by giovannipizzi** [CasperWA/voila-optimade-client#32]
Here:
https://github.com/aiidalab/aiidalab-optimade/blob/a14ae5caf6d2045d341f4c8891ed074022af11c7/aiidalab_optimade/informational.py#L88
The query string is 'url-encoded' by hand, by passing `%23` instead of `#` and doing some replacements.

However this is very fragile, and in particular the content of `log.getAttribute('value')` is not url-encoded. Indeed, when trying to click on the button in production, I get a `503 Gateway error` from GitHub because some `<` and `>` characters are left in. 

Instead, one should write the intended final string, and then use `url lib.parse.urlencode` to safely create and encoded query string.

For instance: `urllib.parse.urlencode({'body': '# some body with < symbols >', 'title': 'Some & title'})` that e.g. returns `body=%23+some+body+with+%3C+symbols+%3E&title=Some+%26+title`

**Comment by CasperWA** [comment]
So I actually _do_ encode `log.getAttribute('value')` in the log handler. However, this is one of those things that happens (and shouldn't happen) when you're simply trying to make something else work. You miss the obvious solutions ...
Will definitely use `urllib` instead, thanks!

**Comment by CasperWA** [comment]
Fixed in #25
