### ISSUE TITLE
The periodic table is truncated

### ISSUE THREAD

**Issue by csadorf** [CasperWA/voila-optimade-client#336]
The periodic table is truncated in a way that some elements are not accessible:

![Screen Shot 2021-08-24 at 13 21 43](https://user-images.githubusercontent.com/1441208/130608217-b432c645-b020-4ed0-add3-60b504caa48c.png)

It is not possible to scroll to the desired elements either.

Version: 2021.8.24
On AiiDAlab.

**Comment by CasperWA** [comment]
Note to self: Fix by pointing to other notebook/moving to vertical layout.
