### ISSUE TITLE
The "Select provider choice" should be more visible

### ISSUE THREAD

**Issue by csadorf** [CasperWA/voila-optimade-client#351]
The "Select provider choice" can currently be easily overlooked (see screenshot). This could be easily remedied by adding an additional header right above the "Select provider" dropdown widget and renaming the dropdown hint to something else.

![optimade-widget-select-provider](https://user-images.githubusercontent.com/1441208/134140759-17491e20-4f22-44f3-86e5-274bb9255499.png)

**Comment by CasperWA** [comment]
This comes from the fact that this header is added as a stand-alone HTML widget in the notebook. For the embedded widget (which is used here) it is not present and should be added manually.
There are two choices:
1. Implement it in the `OptimadeQueryWidget` from `aiidalab_widgets_base.databases` (https://github.com/aiidalab/aiidalab-widgets-base/blob/3c509a5fbfc3e6efbd1f05b650995349174c05ed/aiidalab_widgets_base/databases.py#L127).
2. Have the `OptimadeQueryProviderWidget` from `optimade_client` absorb/embed the header.

**Comment by csadorf** [comment]
> This comes from the fact that this header is added as a stand-alone HTML widget in the notebook. For the embedded widget (which is used here) it is not present and should be added manually.
> There are two choices:
> 
>     1. Implement it in the `OptimadeQueryWidget` from `aiidalab_widgets_base.databases` (https://github.com/aiidalab/aiidalab-widgets-base/blob/3c509a5fbfc3e6efbd1f05b650995349174c05ed/aiidalab_widgets_base/databases.py#L127).
> 
>     2. Have the `OptimadeQueryProviderWidget` from `optimade_client` absorb/embed the header.

Thanks for the quick response! I think I will go with option 1.
